move checking existance of idn_to_ascii function
yiisoft/validator pull request #122
Opened 2021-03-02 11:20 UTC by kriptonuz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #121

2021-03-02 11:22 UTC, vjik approved these changes

2021-03-02 11:41 UTC, viktorprogger requested changes
This behavior should be checked within a test. Here is an example [how to mock the `function_exists` function](https://stackoverflow.com/questions/32007032/is-it-possible-to-mock-the-non-existence-of-a-function-in-phpunit#answer-34386422).

2021-03-02 11:41 UTC, viktorprogger commented on src/Rule/Url.php
> +        }
```suggestion
        if (!function_exists('idn_to_ascii')) {
            throw new \RuntimeException('In order to use IDN validation intl extension must be installed and enabled.');
        }

        $new = clone $this;
```
There is no need to clone the instance if `idn_to_ascii` doesn't exist.

2021-03-02 14:25 UTC, samdark approved these changes
Good change but tests should be added for it.

2021-03-02 22:37 UTC, samdark commented on tests/Rule/UrlTest.php
> +    public static bool $idnFunctionException = false;
Why do we need it if it's not used anywhere?

2021-03-04 13:14 UTC, merged

2021-03-04 13:14 UTC, samdark commented
👍