Adjust doc-blocks, finalize classes, other improvements
yiisoft/validator pull request #146
Opened 2021-12-06 16:45 UTC by rustamwin

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

2021-12-06 17:09 UTC, devanych approved these changes

2021-12-07 06:45 UTC, vjik requested changes

2021-12-07 06:45 UTC, vjik commented on src/DataSetInterface.php
> +     * @throws MissingAttributeException if there is no such value.
```suggestion
     * @throws MissingAttributeException If there is no such value.
```

2021-12-07 08:55 UTC, vjik approved these changes

2021-12-07 09:12 UTC, merged