Enhance tests
yiisoft/validator pull request #199
Opened 2022-04-04 12:04 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #190

2022-04-07 10:15 UTC, samdark approved these changes

2022-04-07 11:32 UTC, vjik requested changes

2022-04-07 11:32 UTC, vjik commented on tests/Rule/EmailTest.php
> -    public function testMalformedAddressesIdnEnabled($value): void
Seems, in process refactoring skipped test mailformed addresses with IDN enabled.

2022-04-07 14:26 UTC, arogachev commented on tests/Rule/EmailTest.php
> -    public function testMalformedAddressesIdnEnabled($value): void
`testMalformedAddressesIdnDisabled` and `testMalformedAddressesIdnEnabled` are actually exactly the same except `function_exists` check in "enabled" test. 

https://github.com/yiisoft/validator/blob/1ce067ebb08120b9c7540fc23cbfbb5000145726/tests/Rule/EmailTest.php#L179-L183
https://github.com/yiisoft/validator/blob/1ce067ebb08120b9c7540fc23cbfbb5000145726/tests/Rule/EmailTest.php#L196-L201

Thought that this was a logical bug and unsafe (exception will be thrown in "disabled" test in case of missing extension). I combined them into one test - if "intl" extension is available, it will run. 

So, maybe vice versa, it's lacking "disabled" check? But it's also missing in current test base. Probably we need to use something like this? 

https://github.com/yiisoft/validator/blob/1ce067ebb08120b9c7540fc23cbfbb5000145726/tests/Rule/UrlTest.php#L204-L213

Suggesting to solve it in other issue then.

2022-04-07 18:29 UTC, vjik commented on tests/Rule/EmailTest.php
> -    public function testMalformedAddressesIdnEnabled($value): void
Seems, here:

https://github.com/yiisoft/validator/blob/1ce067ebb08120b9c7540fc23cbfbb5000145726/tests/Rule/EmailTest.php#L181

IDN should be disabled.

2022-04-08 09:59 UTC, arogachev commented on tests/Rule/EmailTest.php
> -    public function testMalformedAddressesIdnEnabled($value): void
Ah, I forgot about this one. I moved it to test with default arguments, because after removing `enableIdh` it becomes just `new Email()`.

2022-04-08 11:47 UTC, merged