Fix #264: Remove GroupRule in favor of Composite
yiisoft/validator pull request #267
Opened 2022-07-20 15:33 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  | #264

2022-07-20 15:44 UTC, xepozz approved these changes

2022-07-20 15:59 UTC, xepozz requested changes

2022-07-20 15:59 UTC, xepozz commented on src/Rule/Composite.php
>      use HandlerClassNameTrait;
You should delete it and use composite rule handler directly in this class as it was in group rule.

2022-07-20 17:48 UTC, rustamwin approved these changes

2022-07-22 21:00 UTC, xepozz approved these changes

2022-07-22 21:17 UTC, merged