Docs, part 2
yiisoft/validator pull request #408
Opened 2022-11-30 11:54 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #358

2022-11-30 12:13 UTC, vjik requested changes

2022-11-30 12:13 UTC, vjik commented on src/SkipOnEmptyInterface.php
> +     * - `null` and `false` - never skip a rule (the validated value is always considered as not empty). Matching
Null - will be used default empty criteria from validator.

2022-11-30 20:25 UTC, samdark requested changes

2022-11-30 20:25 UTC, samdark commented on src/SkipOnEmptyInterface.php
> + * "empty". Requires an additional private class property `$skipOnEmpty`. In package rules it's `null` by default:
> Requires an additional private class property `$skipOnEmpty`.

Interface can't require a property, especially private one.

2022-11-30 20:25 UTC, samdark commented on src/SkipOnEmptyInterface.php
> + * "empty". Requires an additional private class property `$skipOnEmpty`. In package rules it's `null` by default:
I think that belongs to `SkipOnEmptyTrait` description and not here.

2022-11-30 20:25 UTC, samdark commented on src/SkipOnEmptyInterface.php
> +     * A setter to change `$skipOnEmpty` property. Must be implemented following immutability concept:
Interface knows nothing about how the value is stored so we should not mention implementation details.

2022-11-30 20:25 UTC, samdark commented on src/SkipOnEmptyInterface.php
> +     * A setter to change `$skipOnEmpty` property. Must be implemented following immutability concept:
Immuntability could be mentioned as a requirement, but I don't think an example is needed.

2022-11-30 20:25 UTC, samdark commented on src/SkipOnEmptyInterface.php
> +     * A getter for `$skipOnEmpty` property. Returned value is unchanged. Typical implementation is just a simple
Same here. Should not mention properties. That's not part of the interface.

2022-12-01 08:36 UTC, arogachev commented
The part with default value in `SkipOnEmptyTrait::getSkipOnEmptyOption()` can be handled later - #411.

2022-12-02 07:48 UTC, vjik approved these changes

2022-12-02 10:40 UTC, samdark approved these changes

2022-12-02 11:19 UTC, merged