Phpdoc 4
yiisoft/validator pull request #477
Opened 2022-12-19 20:46 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #358

2022-12-19 20:47 UTC, samdark commented
Arrgh. Wrong branch was used as a base. Review only Email and EmailHandler please.

2022-12-21 11:02 UTC, arogachev commented on src/Rule/Email.php
>      use SkipOnErrorTrait;
Description:

> Validates that the value is a valid email address.

But rule does not perform the actual validation, it's done by handler.

2022-12-21 11:03 UTC, arogachev commented on src/Rule/Email.php
> -        #[Language('RegExp')]
Why language attributes were removed?

2022-12-21 11:05 UTC, arogachev commented on src/Rule/Email.php
> +     * Defaults to false meaning that validation of emails containing IDN will always fail.
```suggestion
     * Defaults to `false` meaning that validation of emails containing IDN will always fail.
```

2022-12-21 11:06 UTC, arogachev commented on src/Rule/Email.php
> +     * otherwise an exception would be thrown.
```suggestion
     * otherwise an exception will be thrown.
```

2022-12-21 11:09 UTC, arogachev commented on src/Rule/Email.php
>          private $skipOnEmpty = null,
```suggestion
        private mixed $skipOnEmpty = null,
```

2022-12-21 11:11 UTC, arogachev requested changes
See suggestions

2022-12-21 11:12 UTC, vjik commented on src/Rule/Email.php
> -        #[Language('RegExp')]
it's cool feature of PhpStorm

2022-12-21 11:28 UTC, arogachev commented on src/Rule/Email.php
>              throw new RuntimeException('In order to use IDN validation intl extension must be installed and enabled.');
Add "throws" tag?

2022-12-22 11:31 UTC, samdark commented on src/Rule/Email.php
> -        #[Language('RegExp')]
It doesn't really work here.

2022-12-22 13:02 UTC, merged