Docs, part 14
yiisoft/validator pull request #493
Opened 2022-12-27 11:08 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #358

2022-12-27 15:21 UTC, vjik requested changes

2022-12-27 15:21 UTC, vjik commented on src/Rule/Json.php
> + * @see BooleanValueHandler Corresponding handler performing the actual validation.
```suggestion
 * @see JsonHandler Corresponding handler performing the actual validation.
```

2022-12-27 15:21 UTC, vjik commented on src/Rule/Subset.php
> + * Nested arrays are supported too in both {@see values} argument and in the validated value (the order of values in
```suggestion
 * Nested arrays are supported too in both {@see $values} argument and in the validated value (the order of values in
```

2022-12-28 14:54 UTC, samdark commented on src/Rule/Required.php
> +     * function (mixed $value, bool $isAttributeMissing): bool
I'd add extra info about what `$isAttributeMissing` is.

2022-12-28 14:54 UTC, samdark commented on src/Rule/RequiredHandler.php
> + * A handler for {@see Required} rule. Validates that the specified value is passed and not empty.
```suggestion
 * A handler for {@see Required} rule. Validates that the specified value is passed and is not empty.
```

2022-12-28 14:54 UTC, samdark commented on src/Rule/RequiredHandler.php
> +     * function (mixed $value, bool $isAttributeMissing): bool
isAttributeMissing should be described.

2022-12-28 14:54 UTC, samdark commented on src/Rule/Subset.php
> + * Nested arrays are supported too in both {@see $values} argument and in the validated value (the order of values in
```suggestion
 * Nested arrays are supported in both {@see $values} argument and in the validated value (the order of values in
```

2022-12-29 08:11 UTC, merged