Remove `skipOnError` from `StopOnError` and simplify it code
yiisoft/validator pull request #497
Opened 2022-12-29 07:30 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️
| Fixed issues  |

2022-12-29 12:34 UTC, arogachev commented
Synced with master changes, resolved merge conflicts. Seems like something is wrong with Github diff again. Locally it's OK. The only changed files:

- `src/Rule/StopOnError.php`
- `src/Rule/StopOnErrorHandler.php`
- `src/ValidationContext.php`
- `src/Validator.php`
- `tests/Rule/StopOnErrorTest.php`

2022-12-29 13:05 UTC, arogachev requested changes
See suggestions.

2022-12-29 13:05 UTC, arogachev commented on src/Rule/StopOnError.php
> + *
```suggestion
 *
 * ```php
 * $rules = [
 *      new SimpleRule1(), // Let's say there is an error.
 *      // Then this rule is skipped completely with all its related rules.
 *      new StopOnError([
 *          new HeavyRule1(), // Skipped.
 *          new HeavyRule2(), // Skipped.
 *     ]),
 *     new SimpleRule2(), // Skipping of intermediate rules depends on `skipOnError` option.
 * ]);
 * ```
 *
 * Use grouping / ordering / `skipOnError` option to achieve the desired effect,
 *
```

2023-01-05 17:36 UTC, vjik commented on src/Validator.php
> +            $context->setParameter(ValidationContext::PARAMETER_PREVIOUS_RULES_ERRORED, true);
Why?

2023-01-05 18:18 UTC, vjik commented on src/ValidationContext.php
> +     */
done

2023-01-05 18:18 UTC, vjik commented on tests/Rule/StopOnErrorTest.php
> +                    ]),
done

2023-01-09 17:57 UTC, arogachev approved these changes

2023-01-09 17:57 UTC, merged