Add messages in Uzbek
yiisoft/validator pull request #511
Opened 2023-01-19 16:41 UTC by mrmuminov

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2023-01-21 07:17 UTC, rustamwin requested changes

2023-01-21 07:17 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'An object data set data can only have an array or an object type.' => 'Maʻlumotlar toʻplami qiymatlari massiv yoki obyekt boʻlishi kerak.',
```suggestion
    'An object data set data can only have an array or an object type.' => 'Obyekt ma\'lumotlari massiv yoki obyekt boʻlishi kerak.',
```

2023-01-21 07:17 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'Value must be a number.' => 'Qiymat haqiqiy raqam boʻlishi kerak.',
```suggestion
    'Value must be a number.' => 'Qiymat raqam boʻlishi kerak.',
```

2023-01-21 07:17 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'Value must be iterable.' => 'Qiymat iteratsiyalangan boʻlishi kerak',
```suggestion
    'Value must be iterable.' => 'Qiymat takrorlanadigan boʻlishi kerak',
```

2023-01-21 07:17 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'This value is not a subset of acceptable values.' => 'Bu qiymat qabul qilinadigan qiymatlar to\'plami emas.',
```suggestion
    'This value is not a subset of acceptable values.' => 'Bu qiymat ruxsat etilgan qiymatlarning quyi toʻplami emas.',
```

2023-01-21 07:17 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'This value is not a valid URL.' => 'Qiymat to\'g\'ri havola emas.',
```suggestion
    'This value is not a valid URL.' => 'Qiymat yaroqli havola emas.',
```

2023-01-23 11:03 UTC, mrmuminov reviewed
Corrections in translation, spelling and plural elements

2023-01-23 13:06 UTC, rustamwin requested changes

2023-01-23 13:06 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'Value must be greater than "{targetValueOrAttribute}".' => 'Qiymat {targetValueOrAttribute} dan katta boʻlishi kerak.',
```suggestion
    'Value must be greater than "{targetValueOrAttribute}".' => 'Qiymat "{targetValueOrAttribute}"dan katta boʻlishi kerak.',
```

2023-01-23 13:06 UTC, rustamwin commented on messages/uz/yii-validator.php
> +    'Value must be greater than or equal to "{targetValueOrAttribute}".' => 'Qiymat {targetValueOrAttribute} dan katta yoki teng boʻlishi kerak.',
```suggestion
    'Value must be greater than or equal to "{targetValueOrAttribute}".' => 'Qiymat "{targetValueOrAttribute}"dan katta yoki teng boʻlishi kerak.',
```

2023-01-23 13:13 UTC, rustamwin approved these changes

2023-01-23 13:15 UTC, merged