Add StopOnError::$skipOnError
yiisoft/validator pull request #555
Opened 2023-02-11 17:55 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

2023-02-12 06:22 UTC, samdark approved these changes

2023-02-13 18:18 UTC, vjik requested changes

2023-02-13 18:18 UTC, vjik commented on src/Rule/StopOnErrorHandler.php
>          }
It's not need. Validator make it, see `Validator::shouldSkipRule()`.

2023-02-14 07:00 UTC, vjik approved these changes

2023-02-14 07:25 UTC, vjik approved these changes

2023-02-14 07:35 UTC, merged