Add StringValue rule
yiisoft/validator pull request #595
Opened 2023-03-14 17:13 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #594

2023-03-15 08:10 UTC, vjik requested changes
Overall good. Several improvements are required:
- line in changelog
- kill mutants

2023-03-15 08:10 UTC, vjik commented on src/RuleInterface.php
> +     * @psalm-return RuleHandlerInterface|class-string
```suggestion
```

Here can be returned identificator for DI-container that not class string.

2023-03-16 05:59 UTC, samdark approved these changes

2023-03-16 11:11 UTC, vjik approved these changes

2023-03-16 11:12 UTC, merged