up php
yiisoft/validator pull request #648
Opened 2024-01-16 18:23 UTC by pamparam83

I upgraded the PHP version to PHP 8.1. 
There were issues with infection, it requires at least 8.1.
 Rector has 8.2.

2024-01-17 07:23 UTC, samdark commented
Please add a line for CHANGELOG.md. Thanks.

2024-01-17 08:53 UTC, vjik requested changes
Need remove code for PHP 8.0 only (search by `PHP_VERSION`) and remove unnecessary version of psalm from composer.json.

2024-01-18 10:36 UTC, vjik approved these changes

2024-01-18 10:37 UTC, merged

2024-01-18 10:37 UTC, vjik commented
Good work 👍