Translate validation section of docs into Russian
yiisoft/validator pull request #667
Opened 2024-03-01 16:46 UTC by ArduanovDanil

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |  ❌

2024-03-01 20:50 UTC, samdark requested changes
Спасибо!

2024-03-01 20:50 UTC, samdark commented on docs/guide/ru/conditional-validation.md
> +Правила содержат несколько вариантов их пропуска при определенных условиях. Не каждое правило поддерживает все эти варианты, но подавляющее большинство поддерживает.
Плохо читается. Можно лучше?

2024-03-02 03:06 UTC, ArduanovDanil commented on docs/guide/ru/conditional-validation.md
> +Правила содержат несколько вариантов их пропуска при определенных условиях. Не каждое правило поддерживает все эти варианты, но подавляющее большинство поддерживает.
Попробовал переформулировать

2024-03-02 09:34 UTC, samdark commented on docs/guide/ru/result.md
> +```
Да, что-то не так. В оригинале так же?

2024-03-02 15:06 UTC, ArduanovDanil commented on docs/guide/ru/result.md
> +```
Да, в оригинале так же. Наверно, должно быть
```php
[
    '3' => ['Value must be no less than 21.'],
],
```
Если так, то PR в оригинал тоже сделаю

2024-03-03 08:29 UTC, samdark commented on docs/guide/ru/result.md
> +```
Вроде так. @vjik верно?

2024-03-22 06:06 UTC, ArduanovDanil commented on docs/guide/ru/result.md
> +```
@vjik тут подправил https://github.com/yiisoft/validator/pull/669

2024-03-26 14:41 UTC, samdark approved these changes

2024-03-26 14:41 UTC, merged