Change type of `$skipOnEmpty` argument in rules' constructors from `mixed` to `bool|callable|null`
yiisoft/validator pull request #698
Opened 2024-04-12 08:33 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ✔️

2024-04-13 06:14 UTC, vjik requested changes
What about another rules: `AtLeast`, `Email`, `In` ?

Need keep in constructor argument only and extract class property to class level:

```php
class {
	public function __construct(
		private mixed $skipOnEmpty = null,
	) {}
}

// ↓

class {
	private mixed $skipOnEmpty;
	public function __construct(
		bool|callable|null $skipOnEmpty = null,
	) {
		$this->skipOnEmpty = $skipOnEmpty;
	}
}
```

2024-04-15 09:52 UTC, arogachev commented
@vjik Done. :heavy_check_mark:

2024-04-26 08:47 UTC, vjik requested changes

2024-04-26 08:47 UTC, vjik commented on src/Rule/Trait/SkipOnEmptyTrait.php
>   * ) {
```suggestion
 * ) {
     $this->skipOnEmpty = $skipOnEmpty;
```

2024-04-26 08:47 UTC, vjik commented on src/Rule/Trait/SkipOnEmptyTrait.php
> +    private mixed $skipOnEmpty;
```suggestion
    private mixed $skipOnEmpty = null;
```

2024-04-26 08:47 UTC, vjik commented on tests/Rule/CompositeTest.php
> -                            $this->rules = [new Required()];
Keep as is. Composite rule must be easy for extend.

2024-04-26 08:47 UTC, vjik commented on tests/Rule/CompositeTest.php
> -                        {
Keep as is. Composite rule must be easy for extend.

2024-04-26 08:48 UTC, vjik commented on src/Rule/Trait/SkipOnEmptyTrait.php
> +    private mixed $skipOnEmpty;
Add info to upgrade.md for users that created own rules with this trait usage.

2024-04-30 13:10 UTC, vjik approved these changes

2024-04-30 13:10 UTC, vjik commented on UPGRADE.md
> +      private mixed $skipOnEmpty = null,
```suggestion
      bool|callable|null $skipOnEmpty = null,
```

2024-04-30 13:11 UTC, vjik commented on UPGRADE.md
> +      $this->skipOnEmpty = $this->skipOnEmpty;
```suggestion
      $this->skipOnEmpty = $skipOnEmpty;
```

2024-04-30 15:50 UTC, merged