Sync with master branch
yiisoft/validator pull request #715
Opened 2024-05-23 09:30 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-05-27 13:12 UTC, vjik requested changes

2024-05-27 13:12 UTC, vjik commented on docs/guide/ru/README.md
Add link to this file from readme in root

2024-05-27 13:12 UTC, vjik commented on docs/guide/ru/README.md
> +- [Built-in rules](built-in-rules.md)
Broken link. Check other links also

2024-05-27 13:12 UTC, vjik commented on messages/de/yii-validator.php
Add line to changelog

2024-05-27 13:12 UTC, vjik commented on src/Exception/UnexpectedRuleException.php
> + *     public function validate(mixed $value, RuleInterface $rule, ValidationContext $context): Result
In this version need `object`.

2024-05-27 13:12 UTC, vjik commented on src/Rule/AtLeast.php
> +        if ($min > count($this->attributes)) {
Add line to changelog

2024-05-27 13:12 UTC, vjik commented on src/Rule/EachHandler.php
> +        $originalEachKey = $context->getParameter(Each::PARAMETER_EACH_KEY);
Add line to changelog

2024-05-28 06:48 UTC, samdark commented
I don't think we need to backport changes from next major version into 1.x.

2024-06-11 12:12 UTC, closed without merging