Add a check result entry to nested forms
yiisoft/validator pull request #748
Opened 2024-09-21 21:30 UTC by DAGpro

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-09-22 08:31 UTC, arogachev requested changes
The tests are needed. What's the purpose of these changes exactly?

2024-09-30 12:26 UTC, samdark commented
@DAGpro so it calls nested object's hooks, right?

2024-09-30 13:36 UTC, DAGpro commented
@samdark right

2024-09-30 13:58 UTC, vjik requested changes
1) Add test with check error path in nested object.
2) Add line to changelog

2024-10-01 14:30 UTC, vjik approved these changes

2024-10-01 15:17 UTC, arogachev approved these changes

2024-10-01 15:17 UTC, arogachev commented on CHANGELOG.md
> +  rules is used (@DAGpro)
```suggestion
```

2024-10-01 15:17 UTC, arogachev commented on CHANGELOG.md
> +- Bug #748: Fix hook processing for nested objects that implement `PostValidationHookInterface` when `Nested` rule with
```suggestion
- Bug #748: Fix hook processing for nested objects that implement `PostValidationHookInterface` when `Nested` rule is used (@DAGpro)
```

2024-10-02 06:45 UTC, vjik commented on CHANGELOG.md
> +- Bug #748: Fix hook processing for nested objects that implement `PostValidationHookInterface` when `Nested` rule is used (@DAGpro)
```suggestion
- Bug #748: Fix hook processing for nested objects that implement `PostValidationHookInterface` when `Nested` rule with
  specified rules is used (@DAGpro)
```

2024-10-02 06:48 UTC, merged

2024-10-02 06:48 UTC, vjik commented
@DAGpro thanks!