Make concept of nested validation rule
yiisoft/validator pull request #98
Opened 2021-01-09 14:31 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #23

2021-01-09 14:32 UTC, xepozz commented
Waiting for https://github.com/yiisoft/arrays/pull/80

2021-01-11 20:28 UTC, roxblnfk commented on tests/Rule/NestedTest.php
> +        $validator = (new Nested(['value' => (new Required())]))
```suggestion
        $validator = (new Nested(['value' => new Required()]))
```

2021-01-11 20:28 UTC, roxblnfk commented on src/Rule/Nested.php
> +        $rules = $rules instanceof Traversable ? iterator_to_array($rules) : (array)$rules;
```suggestion
        $rules = $rules instanceof Traversable ? iterator_to_array($rules) : $rules;
```

2021-01-11 20:28 UTC, roxblnfk commented on src/Rule/Nested.php
> +            fn (bool $carry, $rule) => $carry || is_array($rule) ? $this->checkRules($rule) : !$rule instanceof Rule,
Are you sure about operators priority?

2021-01-23 16:57 UTC, xepozz commented on src/Rule/Nested.php
> +            fn (bool $carry, $rule) => $carry || is_array($rule) ? $this->checkRules($rule) : !$rule instanceof Rule,
Sure

2021-01-24 15:15 UTC, samdark requested changes

2021-01-24 15:15 UTC, samdark commented on src/Rule/Nested.php
> +        return $this->rules->asArray();
There's no `asArray()` in `rules`. Also, there's no test for this method.

2021-01-24 21:02 UTC, samdark approved these changes

2021-01-24 21:03 UTC, merged

2021-01-24 21:03 UTC, samdark commented
:+1